backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "illustration"
    label: "Illustration"
    folder: "projects"
    create: true
    filter: {field: "category", value: "Illustration"}
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Hero Image", name: "hero", widget: "image"}
      - {label: "Category", name: "category", widget: "select", options: ["Illustration", "Character Design"]}
      - {label: "Description", name: "body", widget: "markdown"}
      - label: "Artwork"
        name: "artwork"
        widget: "list"
        fields:
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Alt Text", name: "alt", widget: "string"}
          - {label: "Description", name: "desc", widget: "string", required: false}
  - name: "character_design"
    label: "Character Design"
    folder: "projects"
    create: true
    filter: {field: "category", value: "Character Design"}
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Hero Image", name: "hero", widget: "image"}
      - {label: "Category", name: "category", widget: "select", options: ["Illustration", "Character Design"]}
      - {label: "Description", name: "body", widget: "markdown"}
      - label: "Artwork"
        name: "artwork"
        widget: "list"
        fields:
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Alt Text", name: "alt", widget: "string"}
          - {label: "Description", name: "desc", widget: "string", required: false}