backend:
  name: git-gateway
  branch: netlify # Branch to update (optional; defaults to master)

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "works"
    label: "Works"
    folder: "works"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Work", name: "work", widget: "image"}
      - {label: "Description", name: "desc", widget: "markdown"}