backend:
  name: git-gateway
  branch: netlify # Branch to update (optional; defaults to master)

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "illustration"
    label: "Illustration"
    folder: "artworks"
    create: true
    filter: {field: "category", value: "Illustration"}
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Hero Image", name: "hero", widget: "image"}
      - {label: "Category", name: "category", widget: "select", options: ["Illustration", "Character Design"]}
      - {label: "Full Post", name: "post", widget: "markdown"}
  - name: "character_design"
    label: "Character Design"
    folder: "artworks"
    create: true
    filter: {field: "category", value: "Character Design"}
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Hero Image", name: "hero", widget: "image"}
      - {label: "Category", name: "category", widget: "select", options: ["Illustration", "Character Design"]}
      - {label: "Full Post", name: "post", widget: "markdown"}